config/routes.rb
Danknox::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  resources :posts
  resources :comments, :only => [:create,:update]
  resources :content
  root :to => 'content#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/markdown_renderer.rb
module MarkdownRenderer
  def markdown(text)
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
      :autolink => true, :space_after_headers => true, :fenced_code_blocks => true, :gh_blockcode => true)
    renderer.render(text)
  end  
end
  

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :rememberable, :database_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  class << self
    def find_for_github_oauth(access_token, signed_in_resource=nil)
      logger.info access_token.inspect
      data = access_token.extra['raw_info']
      if user = User.where(:login => data['login']).first
        user
      else # Create a user with a stub password. 
        User.create!(:login => data['login'], :password => Devise.friendly_token[0,20]) 
      end
    end
  
    def new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["user_hash"]
          user.email    = data["email"]
          user.name     = data["name"]
          user.image    = data["image"]
          user.location = data["location"]
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_posts
  after_filter  :ensure_post_exists
  
  private
  
  def load_posts
    @posts = Post.order('created_at desc')
  end
  
  def ensure_post_exists
    @post ||= Post.new
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    @comment.user = signed_in? ? current_user : nil
    if @comment.save
      flash[:notice] = "Comment created successfully."
      redirect_to post_path(@post)
    else
      flash[:alert] = "Problem creating comment."
      redirect_to post_path(@post)
    end
  end
  
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def index
    @post = Post.last
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.create( params[:post] )
    @post.date = Time.now.to_date
    if @post.save
      flash[:notice] = "Post created"
      redirect_to content_index_path
    else
      flash[:alert] = "problem creating post"
      render "content#new"
    end
  end
  
  def show
    @post = Post.find( params[:id] )
  end  
  
  def edit
    @post = Post.find( params[:id] )
  end
  
  def update
    @post = Post.find( params[:id] )
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post updated successfully."
      redirect_to post_path(@post.id)
    else
      flash[:alert] = "Problem updating post."
      render :edit
    end
  end  

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def github
    @user = User.find_for_github_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Github"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def developer
    @user = User.find_for_github_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Github"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end  
  
  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)  
      options = {:hard_wrap => true, :filter_html => true, :autolink => true,
        :no_intraemphasis => true, :fenced_code_blocks => true, :gh_blockcode => true }
      markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
      syntax_highlighter(markdown.render(text)).html_safe
    end  

    def syntax_highlighter(html)  
      doc = Nokogiri::HTML(html)  
      doc.search("//pre").each do |pre|  
        pre.replace Albino.colorize(pre.text.rstrip, :ruby)  
      end  
      doc.to_s  
    end
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/content/index.html.erb
<div class="edit"><%= link_to 'Edit Post', edit_post_path(@post.id) %></div>
<h1><%= @post.title %></h1>
<h2><%= @post.date.to_date.readable_inspect %></h2>
<div class="content">
<%= markdown(@post.body) %>
</div>
<%= render :partial => 'widgets/email_me' %>

app/views/content/new.html.erb
<div class="content">
	<% if alert%>
		<div class="errors"><%= alert %></div>
	<% end %>
	<%= form_for @post, :method => :post do |f| %>
	<h1>New Post</h1>
	<%= f.text_field :title %>
	<h1>Body</h1>
	<%= f.text_area :body %>
	<%= f.submit "Submit" %>
	<% end %>
</div>

app/views/layouts/_notices.html.erb
<% if alert %>
	<div class="flash-message alert"><%= alert %></div>
<% elsif notice %>
	<div class="flash-message notice"><%= notice %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Danknox</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="main-body">
	<div class="container">
		<div class="container-two">
			<div class="threedot"></div>
			<div class="cloud"></div>
			<div class="danknox"></div>
			<div class="navbar">
				<div class="navbar-left"></div>
				<div class="navbar-middle">
					<%= render :partial => 'menus/navigation' %>
				</div>
				<div class="navbar-right"></div>
			</div>
			<div class="recent">
				<%= render :partial => 'widgets/recent_posts' %>
				<%= render :partial => 'widgets/search' %>
				<%= render :partial => 'widgets/user_account' %>
			</div>
			<div class="main">
				<div class="content-container">
					<%= render :partial => 'layouts/notices' %>
					<%= yield %>
				</div>
			</div>
		</div>
		<%= render :partial => 'widgets/comments' %>
		<div class="footer">
			Copyright Dan Knox 2012
			<div class="float-right"><%= link_to "New Post", new_post_path %></div>
		</footer>
	</div>
</body>
</html>

app/views/menus/_navigation.html.erb
<ul class="navbar-ul">
	<li class="home active"><%= link_to image_tag('home.png'), root_path, :class => 'home' %></li>
	<li class=""><%= link_to image_tag('about.png'), nil, :class => 'about' %></li>
	<li class=""><%= link_to image_tag('contact.png'), nil, :class => 'contact' %></li>
</ul>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<div class="content">
	<%= form_for @post, :method => :put do |f| %>
	<h1>New Post</h1>
	<%= f.text_field :title %>
	<h1>Body</h1>
	<%= f.text_area :body %>
	<%= f.submit "Submit" %>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="content">
	<%= form_for @post, :method => :post do |f| %>
	<h1>New Post</h1>
	<%= f.text_field :title %>
	<h1>Body</h1>
	<%= f.text_area :body %>
	<%= f.submit "Submit" %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="edit"><%= link_to 'Edit Post', edit_post_path(@post.id) %></div>
<h1><%= @post.title %></h1>
<h2><%= @post.date.to_date.readable_inspect %></h2>
<div class="content">
<%= markdown(@post.body) %>
</div>
<%= render :partial => 'widgets/email_me' %>

app/views/widgets/_comments.html.erb
<div class="comment-stats"><%= pluralize(@post.comments.count,'Comment') %></div>

<% @post.comments.each do |comment| %>
<div class="comments">
	<div class="old">
		<font style="color:white;"><%= comment.user.present? ? comment.user.name : 'Guest' %></font> | <font style="color:#E6D22C;"><%= comment.created_at.to_date.readable_inspect %></font><br>
		<br>
		<%= comment.comment %>
	</div>
</div>
<% end %>
<div class="comments">
	<div class="new">
		<%= form_for Comment.new, :url => comments_path(:post_id => @post.id) do |f| %>
		<%= link_to 'Sign in with Github', user_omniauth_authorize_path(:github) unless signed_in? %>
		<table>
			<tr>
				<% if signed_in? %>
				<td colspan="2">Commenting as <%= current_user.name %></td>
				<% else %>
				<td colspan="2">Commenting as Guest.</td>
				<% end %>
			</tr>
			<tr>
				<td>Comment:</td>
				<td><%= f.text_area :comment %></td>
			</tr>
		</table>
		<%= submit_tag 'Comment' %>
		<% end %>
	</div>
</div>

app/views/widgets/_email_me.html.erb
<div class="email-me">Thoughts, questions? <%= link_to 'Email me', 'mailto:dknox@threedotloft.com' %> or leave a comment.</div>

app/views/widgets/_recent_posts.html.erb
<div class="recent-title"></div>
<ul class="recent-ul">
	<% @posts.each do |post| %>
	<li><%= link_to post.title, post_path(post.id) %></li>
	<% end %>
</ul>

app/views/widgets/_search.html.erb
<div class="search-box"><input type="text" class="search" placeholder='Search'></div>

app/views/widgets/_user_account.html.erb
<div class="user-account">
<% if signed_in? %>
	Signed in as: <%= current_user.name %><br><br>
	Not you? <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
<% else %>
	<%= link_to 'Sign in with Github', user_omniauth_authorize_path(:github) %><br><br>
	<% unless Rails.env.production? %>
	<%= link_to 'Sign in with Developer', user_omniauth_authorize_path(:developer) %>
	<% end %>
<% end %>
</div>